In [14]:
import pandas as pd
import numpy as np
import nltk
import re

In [15]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
data = {
    "label": [
        "spam", "ham", "spam", "ham", "spam", "ham",
        "spam", "ham", "spam", "ham"
    ],
    "message": [
        "Win free money now",
        "How are you doing today",
        "Claim your free reward",
        "Let's meet tomorrow",
        "Congratulations you won iphone",
        "Call me when you are free",
        "Get cash prize instantly",
        "I am coming home",
        "Exclusive offer click now",
        "See you in class"
    ]
}

df = pd.DataFrame(data)
df

  label                         message
0  spam              Win free money now
1   ham         How are you doing today
2  spam          Claim your free reward
3   ham             Let's meet tomorrow
4  spam  Congratulations you won iphone
5   ham       Call me when you are free
6  spam        Get cash prize instantly
7   ham                I am coming home
8  spam       Exclusive offer click now
9   ham                See you in class

In [18]:
df["label"] = df["label"].map({
    "ham": 0,
    "spam": 1
})

df

   label                         message
0      1              Win free money now
1      0         How are you doing today
2      1          Claim your free reward
3      0             Let's meet tomorrow
4      1  Congratulations you won iphone
5      0       Call me when you are free
6      1        Get cash prize instantly
7      0                I am coming home
8      1       Exclusive offer click now
9      0                See you in class

In [19]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [20]:
ps = PorterStemmer()

In [21]:
def transform_text(text):
    text = text.lower()

    words = nltk.word_tokenize(text)

    cleaned_words = []

    for word in words:
        if word.isalnum():
            if word not in stopwords.words("english"):
                cleaned_words.append(ps.stem(word))

    return " ".join(cleaned_words)

In [23]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [24]:
df["transformed"] = df["message"].apply(transform_text)
df

   label                         message               transformed
0      1              Win free money now            win free money
1      0         How are you doing today                     today
2      1          Claim your free reward         claim free reward
3      0             Let's meet tomorrow         let meet tomorrow
4      1  Congratulations you won iphone           congratul iphon
5      0       Call me when you are free                 call free
6      1        Get cash prize instantly  get cash prize instantli
7      0                I am coming home                 come home
8      1       Exclusive offer click now        exclus offer click
9      0                See you in class                 see class

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tfidf = TfidfVectorizer(max_features=3000)

In [27]:
X = tfidf.fit_transform(df["transformed"]).toarray()
y = df["label"].values

In [28]:
print(X.shape)
print(y.shape)

(10, 23)
(10,)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [31]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [35]:
pred = model.predict(X_test)
print(pred)

[0 0]

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy = accuracy_score(y_test, pred)
print("Accuracy:", accuracy)

Accuracy: 0.5

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
cm = confusion_matrix(y_test, pred)
print(cm)

[[1 0]
 [1 0]]

In [40]:
def predict_spam(message):
    processed = transform_text(message)
    vector = tfidf.transform([processed]).toarray()
    prediction = model.predict(vector)[0]

    if prediction == 1:
        return "Spam"
    else:
        return "Ham"

In [43]:
msg1 = "Money"
print(predict_spam(msg1))

Spam