In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("work/pandas/sampledata1.csv")

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [ ]:
df["Country"].unique()

<ArrowStringArray>
['United States']
Length: 1, dtype: str

In [ ]:
df["City"].value_counts()

City
New York City        915
Los Angeles          747
Philadelphia         537
San Francisco        510
Seattle              428
                    ...
Aberdeen               1
Hagerstown             1
Arlington Heights      1
San Luis Obispo        1
Springdale             1
Name: count, Length: 531, dtype: int64

In [ ]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.groupby("State")["Profit"].mean().sort_values(ascending=False)[:20]

State
Vermont                 204.088936
Rhode Island            130.100523
Indiana                 123.375411
Montana                 122.221900
Minnesota               121.608847
District of Columbia    105.958930
Delaware                103.930988
Wyoming                 100.196000
Missouri                 97.518341
Michigan                 95.934069
Alabama                  94.865989
Georgia                  88.315453
Nevada                   85.045279
Virginia                 83.026564
Kentucky                 80.573357
Wisconsin                76.380004
New Jersey               75.176260
Oklahoma                 73.544788
Maryland                 66.963608
Arkansas                 66.811452
Name: Profit, dtype: float64

In [ ]:
df.groupby("Product Name")["Sales"].mean().sort_values(ascending=False)[0:20]

Product Name
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480000
Canon imageCLASS 2200 Advanced Copier                                          12319.964800
Cubify CubeX 3D Printer Triple Head Print                                       7999.980000
3D Systems Cube Printer, 2nd Generation, Magenta                                7149.945000
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       6124.965000
High Speed Automatic Electric Letter Opener                                     5676.770667
Ibico EPK-21 Electric Binding System                                            5291.972000
Lexmark MX611dhe Monochrome Laser Printer                                       4207.475250
Canon imageCLASS MF7460 Monochrome Digital Laser Multifunction Copier           3991.980000
Okidata MB760 Printer                                                           3917.200000
Ativa V4110MDD Micro-Cut Shredder                                               3849.945000
Cubify CubeX 3D Printer Double Head Print                                       3699.987667
Zebra ZM400 Thermal Label Printer                                               3482.850000
Hewlett-Packard Desktjet 6988DT Refurbished Printer                             3404.500000
Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish                   3122.193120
Hewlett-Packard Deskjet 3050a All-in-One Color Inkjet Printer                   3040.000000
GBC DocuBind P400 Electric Binding System                                       2994.178000
Canon PC1060 Personal Laser Copier                                              2904.958500
Martin Yale Chadless Opener Electric Letter Opener                              2776.033333
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     2745.338400
Name: Sales, dtype: float64

In [ ]:
df.groupby("Category")["Sales"].mean()

Category
Furniture          349.834887
Office Supplies    119.324101
Technology         452.709276
Name: Sales, dtype: float64

In [ ]:
df["Order Date"]

0        11/8/2016
1        11/8/2016
2        6/12/2016
3       10/11/2015
4       10/11/2015
           ...
9989     1/21/2014
9990     2/26/2017
9991     2/26/2017
9992     2/26/2017
9993      5/4/2017
Name: Order Date, Length: 9994, dtype: str

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d%m%Y")

In [ ]:
df["Order Date"]

0      2016-11-08
1      2016-11-08
2      2016-06-12
3      2015-10-11
4      2015-10-11
          ...
9989   2014-01-21
9990   2017-02-26
9991   2017-02-26
9992   2017-02-26
9993   2017-05-04
Name: Order Date, Length: 9994, dtype: datetime64[us]