# Model Training

In [40]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:
import pandas as pd

path = "/content/drive/MyDrive/data/employee_salary_200.csv"

df = pd.read_csv(path)

In [42]:
df.head()

   Age  Experience Education_Level  Hours_Per_Week  Salary
0   49          21        Bachelor              41  110078
1   35           9        Bachelor              53   69743
2   28           4          Master              50   59444
3   41          16        Bachelor              37   88932
4   39          14        Bachelor              55   99037

In [43]:
df.shape

(200, 5)

In [44]:
df.columns

Index(['Age', 'Experience', 'Education_Level', 'Hours_Per_Week', 'Salary'], dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              200 non-null    int64
 1   Experience       200 non-null    int64
 2   Education_Level  200 non-null    object
 3   Hours_Per_Week   200 non-null    int64
 4   Salary           200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [46]:
df.describe()

              Age  Experience  Hours_Per_Week        Salary
count  200.000000  200.000000      200.000000     200.00000
mean    37.865000   13.550000       42.695000   92311.22000
std     10.590921   10.331564        7.864555   41888.09376
min     21.000000    0.000000       30.000000   30000.00000
25%     28.000000    3.000000       35.000000   56039.25000
50%     38.000000   14.000000       43.500000   94192.50000
75%     47.000000   23.000000       50.000000  127052.25000
max     55.000000   33.000000       55.000000  175877.00000

In [47]:
df.isnull().sum()

Age                0
Experience         0
Education_Level    0
Hours_Per_Week     0
Salary             0
dtype: int64

In [48]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [ ]:
x = pd.get_dummies(x, columns=["Education_Level"])

In [67]:
x["Education_Level_Bachelor"] = x["Education_Level_Bachelor"].astype(int)
x["Education_Level_Master"] = x["Education_Level_Master"].astype(int)
x["Education_Level_PhD"] = x["Education_Level_PhD"].astype(int)

In [68]:
x.head()

,Age,Experience,Hours_Per_Week,Education_Level_Bachelor,Education_Level_Master,Education_Level_PhD
0,49,21,41,1,0,0
1,35,9,53,1,0,0
2,28,4,50,0,1,0
3,41,16,37,1,0,0
4,39,14,55,1,0,0

In [70]:
df["Education_Level"].value_counts()

Education_Level
Bachelor    116
Master       60
PhD          24
Name: count, dtype: int64

In [51]:
y.head()

0    110078
1     69743
2     59444
3     88932
4     99037
Name: Salary, dtype: int64

In [71]:
x.shape

(200, 6)

In [53]:
y.shape

(200,)

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((160, 6), (40, 6))

In [74]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

model = LinearRegression()
scaler = StandardScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

model.fit(X_train_scaled, y_train)

y_prediction = model.predict(X_test_scaled)

In [77]:
from sklearn.metrics import r2_score

score = r2_score(y_test, y_prediction)

score

0.9869685844354589