In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [3]:
df = pd.read_csv("used_appliances.csv")

In [4]:
df.head()

,appliance_type,brand,condition,city,has_warranty,age_years,price_kwd
0,Air Conditioner,Panasonic,Fair,Fahaheel,0,6,141.67
1,Microwave,Orient,Fair,Fahaheel,1,5,41.01
2,Dishwasher,LG,Good,Ahmadi,0,4,145.70
3,Dishwasher,Dawlance,Poor,Riqqa,0,9,66.31
4,Air Conditioner,Dawlance,Good,Salmiya,0,3,165.64

In [5]:
df.dtypes

appliance_type     object
brand              object
condition          object
city               object
has_warranty        int64
age_years           int64
price_kwd         float64
dtype: object

In [6]:
df.nunique()

appliance_type      5
brand               8
condition           4
city               12
has_warranty        2
age_years          10
price_kwd         496
dtype: int64

In [7]:
le = LabelEncoder()

In [8]:
df["brand_label"] = le.fit_transform(df["brand"])

In [9]:
df[['brand', 'brand_label']].head()

       brand  brand_label
0  Panasonic            4
1     Orient            3
2         LG            2
3   Dawlance            0
4   Dawlance            0

In [10]:
condition_order = [['Poor', 'Fair', 'Good', 'Excellent']]

In [11]:
ord_enc = OrdinalEncoder(categories=condition_order)

In [12]:
df["condition_ord"] = ord_enc.fit_transform(df[["condition"]])

In [13]:
df[["condition", "condition_ord"]].drop_duplicates().sort_values("condition_ord")

   condition  condition_ord
3       Poor            0.0
0       Fair            1.0
2       Good            2.0
6  Excellent            3.0

In [14]:
ohe = OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=False)
encoded = ohe.fit_transform(df[["appliance_type"]])

In [15]:
ohe_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['appliance_type']))

In [16]:
pd.concat([df[['appliance_type']], ohe_df], axis=1).head()

,appliance_type,appliance_type_Dishwasher,appliance_type_Microwave,appliance_type_Refrigerator,appliance_type_Washing Machine
0,Air Conditioner,0.0,0.0,0.0,0.0
1,Microwave,0.0,1.0,0.0,0.0
2,Dishwasher,1.0,0.0,0.0,0.0
3,Dishwasher,1.0,0.0,0.0,0.0
4,Air Conditioner,0.0,0.0,0.0,0.0

In [17]:
df.size

4500

In [1]:
import numpy as np

In [ ]:
activity_points = np.array()